In [3]:
import numpy as np
#array creation
a=np.array([1,3,4,6,8])
b=np.array([[1,2,3],[4,5,6]])

type(a)

numpy.ndarray

In [4]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [5]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [6]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.random.rand(2,9)

array([[0.75030944, 0.92530368, 0.36237245, 0.78358349, 0.69387378,
        0.31818852, 0.94592206, 0.12737045, 0.3065433 ],
       [0.13177964, 0.24563821, 0.90776674, 0.4339515 , 0.25364389,
        0.13681865, 0.2187327 , 0.34781796, 0.4271929 ]])

In [22]:
[np.random.randint(2,9) for _ in range(5)]



[3, 7, 6, 4, 4]

In [11]:
np.random.randn(3,5)

array([[-1.04136182,  0.9626129 , -0.23364362,  0.754953  , -0.59327375],
       [ 1.27016757, -0.12738875, -1.00454429, -0.95895307, -0.32597872],
       [-0.83904622, -0.22212603,  0.01261101,  0.56546309,  0.558924  ]])

In [24]:
#array properties
b.shape

(2, 3)

In [27]:
print(a.ndim)
print(a.size)
print(a.dtype)

1
5
int64


In [14]:
a.ndim

1

In [15]:
#array reshapping
b.reshape(2,3)
b.reshape(-1,1)


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [16]:
c=np.array([[2,3],[4,6]])
c1=c.flatten()
c[0]=8
print(c)
print(c1)


[[8 8]
 [4 6]]
[2 3 4 6]


In [17]:
c=np.array([[2,3],[4,6]])
c1=c.ravel()
c[0]=8
print(c)
print(c1)


[[8 8]
 [4 6]]
[8 8 4 6]


In [18]:
e=np.array([[[1,4,6,7],[5,9,56,3]],[[2,34,78,1],[8,4,32,6]]])
e[1][0][3]

np.int64(1)

In [19]:
e=np.array([[[1,4,6,7],[5,9,56,3]],[[2,34,78,1],[8,4,32,6]]])
e[1:4]

array([[[ 2, 34, 78,  1],
        [ 8,  4, 32,  6]]])

In [20]:
#boolean filtering
e[e>10]

array([56, 34, 78, 32])

In [38]:
e
np.sum(e)
np.sum(e,axis=0)#column wise
np.sum(e,axis=1)#eow wise 

array([[  6,  13,  62,  10],
       [ 10,  38, 110,   7]])

In [40]:
np.vstack(e)

array([[ 1,  4,  6,  7],
       [ 5,  9, 56,  3],
       [ 2, 34, 78,  1],
       [ 8,  4, 32,  6]])

In [41]:
np.hstack(e)

array([[ 1,  4,  6,  7,  2, 34, 78,  1],
       [ 5,  9, 56,  3,  8,  4, 32,  6]])

In [44]:
#broadcasting
n=np.array([[1,2,3],[4,5,6]])
m=np.array([5,2,6])
r=n+m
r

array([[ 6,  4,  9],
       [ 9,  7, 12]])