In [3]:
import numpy as np
#array creation
a=np.array([1,3,4,6,8])
b=np.array([[1,2,3],[4,5,6]])

type(a)

numpy.ndarray

In [4]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [5]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [6]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [8]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.random.rand(2,9)

array([[0.36674382, 0.00881416, 0.54411943, 0.79152793, 0.6885108 ,
        0.63894751, 0.39311639, 0.69180301, 0.95494167],
       [0.36455751, 0.1437703 , 0.1204593 , 0.17953093, 0.56067156,
        0.16893364, 0.12280973, 0.99069544, 0.15012859]])

In [10]:
[np.random.randint(2,9) for _ in range(5)]

[5, 7, 6, 8, 3]

In [11]:
np.random.randn(3,5)

array([[-0.48302273,  0.96359058, -0.18561574, -0.46599024, -1.25563072],
       [-0.43468956, -0.38175262,  0.82583913, -2.0501931 ,  0.8584158 ],
       [ 0.34018327,  0.42444697, -0.96768381,  0.34140226, -0.61186253]])

In [12]:
#array properties
b.shape

(2, 3)

In [13]:
print(a.ndim)
print(a.size)
print(a.dtype)

1
5
int64


In [14]:
a.ndim

1

In [15]:
#array reshapping
b.reshape(2,3)
b.reshape(-1,1)


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [16]:
c=np.array([[2,3],[4,6]])
c1=c.flatten()
c[0]=8
print(c)
print(c1)


[[8 8]
 [4 6]]
[2 3 4 6]


In [17]:
c=np.array([[2,3],[4,6]])
c1=c.ravel()
c[0]=8
print(c)
print(c1)


[[8 8]
 [4 6]]
[8 8 4 6]


In [18]:
e=np.array([[[1,4,6,7],[5,9,56,3]],[[2,34,78,1],[8,4,32,6]]])
e[1][0][3]

np.int64(1)

In [19]:
e=np.array([[[1,4,6,7],[5,9,56,3]],[[2,34,78,1],[8,4,32,6]]])
e[1:4]

array([[[ 2, 34, 78,  1],
        [ 8,  4, 32,  6]]])

In [20]:
#boolean filtering
e[e>10]

array([56, 34, 78, 32])

In [21]:
e
#aggregation
np.sum(e)
np.sum(e,axis=0)#column wise
np.sum(e,axis=1)#eow wise 

array([[  6,  13,  62,  10],
       [ 10,  38, 110,   7]])

In [22]:
#stack
np.vstack(e)

array([[ 1,  4,  6,  7],
       [ 5,  9, 56,  3],
       [ 2, 34, 78,  1],
       [ 8,  4, 32,  6]])

In [23]:
np.hstack(e)

array([[ 1,  4,  6,  7,  2, 34, 78,  1],
       [ 5,  9, 56,  3,  8,  4, 32,  6]])

In [24]:
#broadcasting
n=np.array([[1,2,3],[4,5,6]])
m=np.array([5,2,6])
r=n+m
r

array([[ 6,  4,  9],
       [ 9,  7, 12]])

In [32]:
#statistic operation
np.var(e)
np.std(e)
np.median(e)
np.mean(e)
np.min(e)
np.max(e)

np.int64(78)

In [37]:
#seed function
np.random.seed(42)
np.random.normal(3,1)

3.496714153011233

In [39]:
#argsort
np.argsort(e)
np.sort(e)

array([[[ 1,  4,  6,  7],
        [ 3,  5,  9, 56]],

       [[ 1,  2, 34, 78],
        [ 4,  6,  8, 32]]])