In [1]:
import pandas as pd
import numpy as np

In [2]:
d=pd.read_csv("Salary_Data.csv")

In [3]:
d

,Age,Gender,Education Level,Job Title,Years of Experience,Salary
0,32.0,Male,Bachelor's,Software Engineer,5.0,90000.0
1,28.0,Female,Master's,Data Analyst,3.0,65000.0
2,45.0,Male,PhD,Senior Manager,15.0,150000.0
3,36.0,Female,Bachelor's,Sales Associate,7.0,60000.0
4,52.0,Male,Master's,Director,20.0,200000.0
...,...,...,...,...,...,...
6699,49.0,Female,PhD,Director of Marketing,20.0,200000.0
6700,32.0,Male,High School,Sales Associate,3.0,50000.0
6701,30.0,Female,Bachelor's Degree,Financial Manager,4.0,55000.0
6702,46.0,Male,Master's Degree,Marketing Manager,14.0,140000.0


In [4]:
d.columns[d.isna().any()]

Index(['Age', 'Gender', 'Education Level', 'Job Title', 'Years of Experience',
       'Salary'],
      dtype='object')

In [5]:
d[["Years of Experience","Salary"]]=d[["Years of Experience","Salary"]].fillna(d[["Years of Experience","Salary"]].mean())

In [6]:
d=d[["Years of Experience","Salary"]]

In [7]:
pip install Scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x=d[["Years of Experience"]]
y=d["Salary"]

In [12]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.7,random_state=42)

In [13]:
from sklearn.linear_model import LinearRegression

In [14]:
lr=LinearRegression()
lr.fit(x_train,y_train)

,fit_intercept,True
,copy_X,True
,tol,1e-06
,n_jobs,None
,positive,False


In [20]:
y_pre=lr.predict(x_test)
y_pre

array([192634.474479  , 114754.49957938,  79354.51098865, ...,
        58114.5178342 ,  79354.51098865,  72274.5132705 ], shape=(2012,))

In [16]:
from sklearn.metrics import r2_score

In [21]:
r2_score(y_test,y_pre)

0.6434486563267621

In [22]:
lr.coef_

array([7079.99771815])

In [27]:
lr.intercept_

np.float64(58114.517834204795)

In [28]:
i = np.array(2.5).reshape(-1,1)

In [29]:
a = lr.predict(i)
a

C:\Users\Dhanushri\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([75814.51212957])